### ISSUE TITLE
MongoDB import changes `somekey: 1` to `somekey: NumberLong(1)`

### ISSUE THREAD

**Issue by dpc** [mongodb/bson-rust#108]
I've been using `mongo_driver` that uses `bson` to import some data that I've exported with `mongoexport` (so in Strict mode). First I had problems with date parsing (#107), then I've noticed that normal numbers are needlessly converted to `NumberLong` version.

I might look into it tomorrow, but if anyone has any guesses where to look, it would help a lot.

BTW. I'm either confused, or the code is incorrectly calling "Strict Mode" , "the extended" one. From what I understand the "Extended JSON" is the one that MongoDB uses everywhere with `ObjectID` etc. It's extended because it's nor really correct JSON per-se. The one that converts these fancy type-wrapper to  proper JSON, is "Strict Mode". So `from_extended_document` should probably be called `from_strict_mode_document`.

**Comment by patrickfreed** [comment]
If you check out the [extended JSON specification](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#special-rules-for-parsing-json-numbers), it mentions that the behavior this crate exhibits when deserializing JSON numbers is correct:

>If the number is a non-integer, parsers SHOULD interpret it as BSON Double.

>If the number is an integer, parsers SHOULD interpret it as being of the smallest BSON integer type that can represent the number exactly. If a parser is unable to represent the number exactly as an integer (e.g. a large 64-bit number on a 32-bit platform), it MUST interpret it as a BSON Double even if this results in a loss of precision. The parser MUST NOT interpret it as a BSON String containing a decimal representation of the number.

e.g.
```rust
let int32_json = json!(5);
let int64_json = json!(i32::MAX as i64 + 1);
let double_json = json!(i64::MAX as f64 + 1.0);

println!("{:?}", Bson::try_from(int32_json).unwrap());
println!("{:?}", Bson::try_from(int64_json).unwrap());
println!("{:?}", Bson::try_from(double_json).unwrap());
```
yields:
```
Int32(5)
Int64(2147483648)
Double(9223372036854776000.0)
```
