### ISSUE TITLE
GeoJSON Objects

### ISSUE THREAD

**Issue by karasjoh000** [mongodb/bson-rust#115]
is there support for GeoObjects? https://docs.mongodb.com/manual/reference/geojson/#point

**Comment by zonyitoo** [comment]
I don't think it is part of bson's spec?

**Comment by nevi-me** [comment]
You could create your own, though not ideal if you mix points with other types:

```rust
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Point {
    #[serde(rename = "type")]
    pub geo_type: String,
    pub coordinates: Vec<f64>,
}

#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct LineString {
    #[serde(rename = "type")]
    pub geo_type: String,
    pub coordinates: Vec<Vec<f64>>,
}
```

**Comment by saghm** [comment]
Since this is not part of the BSON spec and can be done manually as described in the latest comment, I'm going to close this issue.
