### ISSUE TITLE
 problem on DateTime<Utc> type

### ISSUE THREAD

**Issue by phantomxe** [mongodb/bson-rust#121]
Hi,
https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/317#issue-465699554

That's my issue. Mongodb-labs chose not to deal with my problem.

**Comment by zonyitoo** [comment]
The message `"a formatted date and time string or a unix timestamp"` comes from https://docs.rs/chrono/0.4.0/src/chrono/datetime.rs.html#835 . I am not sure what was happening, could you provide a single reproducible example?

**Comment by zonyitoo** [comment]
I don't think there was anything related to the `doc!` macro, the error happened in deserialization.

**Comment by zonyitoo** [comment]
I finally figured out why!!!

Your problem was when creating fields with `DateTime<Utc>` with `doc!` macro, it was serialized to bson's datetime type correctly, but if you serialized with serde (a struct), datetime become a string.

Try to do this:

```rust
use bson::UtcDateTime;

struct MyStructType {
    pub creatingDate: UtcDateTime,
}

let a = MyStructType {
    creatingDate: UtcDateTime(DateTime<Utc>::new()),
};
```

**Comment by kobenauf** [comment]
This problem still exists.

**Comment by saghm** [comment]
Have you tried using the `UtcDateTime` type instead of the `chrono::DateTime<Utc>` type like zonyitoo suggested? I'm not sure there's anything we can do to work around the fact that `chrono` has it's own implementation of `Serialize` for its `DateTime` type with semantics that don't match how BSON represents dates; that's why we provide a wrapper around it that serializes it to a BSON datetime.

**Comment by kobenauf** [comment]
Sorry, I'm new to Rust, so I am very possibly doing something wrong.  This code:
```
pub struct Org {
  date_created: bson::UtcDateTime,
}
impl Default for Org {
  fn default() -> Org {
    date_created: bson::UtcDateTime(Utc::now()),
  }
}
impl Org {
  fn to_Doc(&self) -> Document {
    doc! {
      "date_created": self.date_created,
    }
  }
}
```
Leads to this error on the `doc!` block of code:
```
the trait bound `bson::bson::Bson: std::convert::From<bson::bson::UtcDateTime>` is not satisfied

the trait `std::convert::From<bson::bson::UtcDateTime>` is not implemented for `bson::bson::Bson`

help: the following implementations were found:
        <bson::bson::Bson as std::convert::From<&'a std::string::String>>
        <bson::bson::Bson as std::convert::From<&'a str>>
        <bson::bson::Bson as std::convert::From<(bson::spec::BinarySubtype, std::vec::Vec<u8>)>>
        <bson::bson::Bson as std::convert::From<(std::string::String, bson::ordered::OrderedDocument)>>
      and 15 others
note: required by `std::convert::From::from`
```

**Comment by saghm** [comment]
I think the key point of confusion here is that there are two different ways to create documents, namely, the `doc!` macro and serde serialization. For the former, you need to give something that can be converted to the [`Bson`](https://docs.rs/bson/0.14.0/bson/enum.Bson.html) type. To pass a `DateTime` into the `doc!` macro, you can just pass it in using the [`Bson::UtcDatetime`](https://docs.rs/bson/0.14.0/bson/enum.Bson.html#variant.UtcDatetime) variant of the `Bson` enum. However, putting `Bson` as the type of your field means that you can't guarantee that some other variant of `Bson` would appear in the field. To work around that, we provide the [`UtcDateTime`](https://docs.rs/bson/0.14.0/bson/struct.UtcDateTime.html) struct, which you can put as a field type. It's a thin wrapper around the chrono `DateTime` type, so you can just access the `DateTime` field when you need to convert to the `Bson` enum for use with the `doc!` macro. Putting it all together, you'd get something like this:

```rust
use bson::{Bson, UtcDateTime};
use chrono::Utc;

#[derive(Serialize, Deserialize)]
pub struct Org {
    date_created: UtcDateTime,
}
impl Default for Org {
    fn default() -> Org {
        date_created: UtcDateTime(Utc::now()),
    }
}
impl Org {
    fn to_doc(&self) -> Document {
        doc! {
            "date_created": Bson::DateTime(self.date_created),
        }
    }
}

fn main() {
    // Create a new `Org` with the current time.
    let org = Org::default();

    // Print the `Org` converted manually to a document.
    println!("{}", org.to_doc());

    // Print the `Org` converted to BSON with serde:
    println!("{}", bson::to_bson(&org).unwrap());
}
```

**Comment by kobenauf** [comment]
This seems very close (and thanks for your help!) but I am getting another error on this line:
```
"date_created": Bson::DateTime(self.date_created.0),
```
```
no variant or associated item named `DateTime` found for type `bson::bson::Bson` in the current scope

variant or associated item not found in `bson::bson::Bson`
```
When I look at the Bson code, I see an enum with lots of types, including UtcDatetime, TimeStamp, and others, but no DateTime.  I really am a noob so I may be missing something else like not importing or initializing something?

**Comment by saghm** [comment]
Ah, yeah, that was just a typo on my part; it should be `Bson::UtcDateTime`. I'll edit it.

**Comment by davyzhang** [comment]
It takes me hours to figure out that difference between 

`bson::Bson::UtcDatetime`
and 
`bson::UtcDateTime`

is just an uppercase.

Can we make them consistent? or utterly different from each other?

**Comment by saghm** [comment]
We happen to have that change (among others) in review right now! https://github.com/mongodb/bson-rust/pull/164/files

**Comment by patrickfreed** [comment]
`bson::UtcDateTime` has since been renamed to `bson::DateTime`. I filed RUST-508 to track work for better documenting this struct.
