### ISSUE TITLE
Replace 'linked-hash-map' with 'indexmap'

### ISSUE THREAD

**Issue by danclive** [mongodb/bson-rust#134]
Because of the [linked-hash-map](https://crates.io/crates/linked-hash-map) declaration

> **WARNING: THIS PROJECT IS IN MAINTENANCE MODE, DUE TO INSUFFICIENT MAINTAINER RESOURCES**

It has become less active. So can we replace this with a more active [indexmap](https://crates.io/crates/indexmap), which has a similar API.

**Comment by danclive** [comment]
#135

**Comment by saghm** [comment]
I've filed https://jira.mongodb.org/browse/RUST-283 to track both this and the PR
