### ISSUE TITLE
Document u2i feature

### ISSUE THREAD

**Issue by Flowneee** [mongodb/bson-rust#141]
Currently `u2i` feature is not mentioned in documentation, however it is quite useful for converting `serde_json::Value` into BSON. I think it would be great, if it is mentioned in README (and, maybe, crate documentation) with example of how to use it (since it is implemented only for `Encoder`).

**Comment by saghm** [comment]
I've filed https://jira.mongodb.org/browse/RUST-285 to track this issue

**Comment by patrickfreed** [comment]
In `2.0.0`, the behavior associated with this feature will be enabled by default, and the flag will be removed, so going to close this out.
