### ISSUE TITLE
correct way deserialize Document to typed struct

### ISSUE THREAD

**Issue by GopherJ** [mongodb/bson-rust#145]
Hello, while using `mongodb-rust` I'm always doing this to get my type:

```rust
let mut my_type: MyType = serde_json::from_str(
        serde_json::to_string(&u_venue_maps)
            .map_err(error::ErrorInternalServerError)?
            .as_str(),
    )
    .map_err(error::ErrorInternalServerError)?;
```

I'm wondering if there is a better way to do it?

**Comment by saghm** [comment]
Hello! I'm not sure I quite understand what you're trying to do here, as you aren't using `bson` anywhere in that code example. In general, if you want to deserialize a `bson::Document` to struct, you can use `bson::from_bson`, which will take anything of type `bson::Bson` and deserialize it based on the inferred return type. Here's a basic example of that:

```rust
use bson::{bson, doc, Bson, Document};

#[derive(Debug, Deserialize)]
struct Point {
    x: i32,
    y: i32,
}

fn main() {
    let doc = doc! {
        "x": 1,
        "y": -2,
    };

    let point: Point = bson::from_bson(Bson::Document(doc));
    println!("{:?}", point); // Prints out "Point { x: 1, y: -2 }"
}
```

**Comment by GopherJ** [comment]
cool sorry I didn't write the correct code but your reply answered the question.  Thanks ! I don't know from_bson api exists
