### ISSUE TITLE
It is recommended to optimize the encode_document and encode_array functions.

### ISSUE THREAD

**Issue by danclive** [mongodb/bson-rust#146]
In our implementation of the function that encodes the Document and Array as bytes, we need to allocate a Vec and encode the elements in it to calculate the length. This causes excess memory allocation.

https://github.com/mongodb/bson-rust/blob/aa4fe08cce629432c5ceacc1ed15177b39380649/src/encoder/mod.rs#L96-L117

I looked at [RawBson](https://github.com/mongodb/bson-rust/issues/133) idea, but RawBson is immutable, and we often need to change documents, so it's not particularly useful in practice.

That's why I recommend whether you can maintain a length message when you're building a Document and an Array, just like that:

```rust
pub struct Document {
    map: IndexMap<String, Bson>,
    len: usize
}

pub struct Array {
    vec: Vec<Bson>,
    len: usize
}
```

This allows you to use this length directly when encode, without having to encode to vec first.

**Comment by koshkin-kna** [comment]
Encoding and decoding of embedded objects and arrays, in principle, work very slowly.
A flat document is processed on the order of ~ 0.002 seconds, while its counterpart with nesting is ~ 0.030 seconds

**Comment by jcdyer** [comment]
Length of a Bson object can be calculated without encoding it.  See the `doc_size_bytes` and `size_bytes` functions in mongodb/mongo-rust-driver:src/bson_util.rs.
