### ISSUE TITLE
key i32  to_bson error

### ISSUE THREAD

**Issue by koshkin-kna** [mongodb/bson-rust#150]
```
let mut x: HashMap<i32, i32> = HashMap::new();
x.insert(2, 4);
bson2::to_bson(&x).unwrap();
```
----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMapKeyType(I32(2))'

**Comment by saghm** [comment]
Hello! BSON only allows strings as keys in documents, so you won't be able to convert a `HashMap` with integer keys to a `Document`.
