### ISSUE TITLE
Any reason for not providing Uuid wrapper just like UtcDataTime?

### ISSUE THREAD

**Issue by AtsukiTak** [mongodb/bson-rust#174]
Hi there! Thanks for all of your great work!

In my project, I want to use Uuid as document field, but it seems not to easy.
When I serialize `Uuid` into `Bson`, it always serialized as `String` because of [its original implementation](https://github.com/uuid-rs/uuid/blob/master/src/serde_support.rs#L23-L24).

I think this situation is pretty similar to `DateTime<Utc>` whose thin wrapper is provided by this crate. 

Is there any reason for not providing `Uuid` wrapper?

If it is provided, it would be very useful for me.

Sorry if I missed something.  I'm pretty new to this crate.

Thanks.

**Comment by AtsukiTak** [comment]
Currently I'm using small conversion function like

```rust
fn uuid_to_bson(uuid: Uuid) -> Bson {
    Bson::Binary(BinarySubtype::Uuid, uuid.as_bytes().to_vec())
}

fn uuid_from_bson(bson: Bson) -> anyhow::Result<Uuid> {
    match bson {
        Bson::Binary(BinarySubtype::Uuid, bytes) => Ok(Uuid::from_slice(bytes.as_slice())?),
        _ => Err(anyhow::anyhow!("given Bson is not Uuid")),
    }
}
```

**Comment by patrickfreed** [comment]
Thanks for filing this issue! I filed [RUST-465](https://jira.mongodb.org/browse/RUST-465) on our jira project to track the work for it.

**Comment by AtsukiTak** [comment]
@patrickfreed Thank you so much!

**Comment by isabelatkinson** [comment]
Hi @AtsukiTak! [RUST-506](https://github.com/mongodb/bson-rust/commit/e03e95e05a8f8da4d71f088c5e06c62488ba77ce) introduces a `uuid_as_binary` module that simplifies working with the `Uuid` type. You can add the following attribute to a `Uuid` field to serialize to and deserialize from BSON Binary:

```
struct Item {
    #[serde(with = "uuid_as_binary")]
    pub id: Uuid,
    // other fields
}
```

**Comment by guija** [comment]
> Currently I'm using small conversion function like
> 
> ```rust
> fn uuid_to_bson(uuid: Uuid) -> Bson {
>     Bson::Binary(BinarySubtype::Uuid, uuid.as_bytes().to_vec())
> }
> 
> fn uuid_from_bson(bson: Bson) -> anyhow::Result<Uuid> {
>     match bson {
>         Bson::Binary(BinarySubtype::Uuid, bytes) => Ok(Uuid::from_slice(bytes.as_slice())?),
>         _ => Err(anyhow::anyhow!("given Bson is not Uuid")),
>     }
> }
> ```

This conversion is not working for me for Rust version 1.70. So I adapted it (especially the restructuring) and implemented a trait for it like this:
```
trait BsonUuidConversion {
    fn as_uuid(&self) -> anyhow::Result<uuid::Uuid>;
}

impl BsonUuidConversion for Bson {
    fn as_uuid(&self) -> anyhow::Result<uuid::Uuid> {
        match self {
            Bson::Binary(binary) => match binary {
                mongodb::bson::binary::Binary {
                    subtype: _BinarySubtype,
                    bytes,
                } => Ok(uuid::Uuid::from_slice(bytes.as_slice())?),
                _ => Err(anyhow::anyhow!("given Bson is not Uuid")),
            },
            _ => Err(anyhow::anyhow!("given Bson is not Uuid")),
        }
    }
}

let bsonUuid : Bson = ...;
let uuid = bsonUuid.as_uuid();
```
