### ISSUE TITLE
Error convert string Json to Document using Serde.

### ISSUE THREAD

**Issue by almir-lima** [mongodb/bson-rust#189]
Hi everyone, i try convert a String JSON to Document, but i receive a error when key value is a Integer, if i put in quotes number then it's work.

it's work:
let d: Document = serde_json::from_str( &"{ \"id\" : \"1\" }".to_string() ).unwrap();

Don't work:
let d: Document = serde_json::from_str( &"{ \"id\" : 1 }".to_string() ).unwrap();

I receive this message below:

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `1`, expected a signed integer", line: 1, column: 10)'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by saghm** [comment]
To convert raw JSON into a `Document`, you'll need to first create a `serde_json::Map`, and then convert that into a `Document`:

```rust
use bson::Document;
use serde_json::{Map, Value};

let value: Map<String, Value> = serde_json::from_str("{ \"id\": 1 }")?;
let document = Document::try_from(value)?;
```

For an arbitrary BSON value, you can substitute `Map` and `Document` with `Value` and `Bson`:

```rust
use bson::Bson;
use serde_json::Value;

let value: Value = serde_json::from_str("1")?;
let bson_value = Bson::try_from(value)?;
```

Alternately, if you're using a custom type with `Serialize` and `Deserialize` to model your data, you can use that as an intermediate form between the JSON and BSON to validate the structure:

```rust
use bson::Bson;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Deserialize, Serialize)]
struct Item {
    id: i32,
}

let item: Item = serde_json::from_str("{ \"id\": 1 }")?;
let bson_value = bson::ser::to_bson(&item)?;
```

**Comment by patrickfreed** [comment]
I filed RUST-507 to track work for deserializing BSON types like this easier. Thank you for filing this issue!

**Comment by njust** [comment]
Hi, I'm trying to convert a raw json to a bson document as described above. Unfortunatelty the Document::try_from method is not public anymore, so I tried 

```rust
    let value: Map<String, Value> = serde_json::from_str("{ \"id\": 1 }")?;
    let document = bson::to_document(&value)?;
```

this compiles, but gives me a error at runtime: `Error: UnsupportedUnsignedType.` My dependencies are:
```

#bson = {git = "https://github.com/mongodb/bson-rust.git"}
bson = "1.1.0"
serde = "1.0.117"
serde_json = "1.0.59"
```

**Comment by isabelatkinson** [comment]
Hi @njust!

We currently have work in progress to deserialize unsigned integers which will be included in the next release. You can take a look at [RUST-507](https://jira.mongodb.org/browse/RUST-507) to track this work. In the meantime, the following code should give you the desired document:
```
let value: Map<String, Value> = serde_json::from_str("{ \"id\": 1 }")?;
let doc = Document::try_from(value)?;
```
In order to use `Document::try_from`, make sure you have `std::convert::TryFrom` included in your imports.

**Comment by njust** [comment]
Hi @isabelatkinson, thanks for helping out.

**Comment by isabelatkinson** [comment]
Hi @njust, the work for [RUST-507](https://github.com/mongodb/bson-rust/commit/9e85122658333a841fe3e7a3cd8ac3568d4179e9) to convert from unsigned to signed automatically during deserialization has been completed and will be included in the next release.
