### ISSUE TITLE
How to merge two bson doc?

### ISSUE THREAD

**Issue by gembin** [mongodb/bson-rust#192]
```JSON
let doc1 = doc! {
  "field1": "value1"
}

let doc2 = doc! {
  "field2": "value2"
}
```
Merged doc:
```JSON
let merged_doc = doc! {
  "field1": "value1",
  "field2": "value2",
}
```
I know there is an API: `doc1.insert("field2", "value2");`
I think it would be great if have an API like this:  `doc1.merge(doc2)`

**Comment by saghm** [comment]
That's a good idea! I think it would make sense to have something like [`Vec::extend`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend) on `Document`.

As a workaround for now, you could chain the iterators of the two documents to create a new one:

```rust
let doc1 = doc! { "x": 1 };
let doc2 = doc! { "y": 2 };
let doc3: Document = doc1.into_iter().chain(doc2).collect();
```

**Comment by patrickfreed** [comment]
I filed [RUST-505](https://jira.mongodb.org/browse/RUST-505) to track the work on this. Thank you for filing an issue!

**Comment by Stargateur** [comment]
what would be the behavior for duplicate key ?

**Comment by saghm** [comment]
That's a good question! My initial instinct is that it should behave as if each key value pair were manually inserted into the left-hand document in the order they appear in the right-hand one. This would mean that the values in the right-hand side would overwrite the ones in the left-hand side. This is what `linked-hash-map` (the dependency we use that underlies our `Document` type) does under the hood [in its own extend method](https://docs.rs/linked-hash-map/0.5.3/src/linked_hash_map/lib.rs.html#727-731), which we'd presumably be wrapping.

For example:

```rust
let mut a = doc! { "x": 1, "y": 2 };
let b = doc! { "x": 3, "z": 4 };
a.extend(b);

assert_eq!(a, doc! { "y": 2, "x": 3, "z": 4 });
```

This definitely is something that could potentially surprise people no matter what we do, though. Specifically, I think it might not be obvious to users why "x" appears after "y" in the result document of the example above. That being said, I still think it's useful enough to include in the API despite that! We'll just need to make sure to document it carefully.

**Comment by saghm** [comment]
We could potentially also include a method that gives users a way to manually resolve conflicts manually. One possible signature for this would be to allow users to pass in a closure that takes in the key name and both values and returns what the new value should be:

```rust
fn merge(&mut self, other: Document, impl Fn(&str, Bson, Bson) -> Bson) { ... }
```

It might get used like this:

```rust
a.merge(b, |key, left_val, right_val| {
    match key {
        "x": right_val,
        _ => left_val + right_val,
    }
})
```

**Comment by Stargateur** [comment]
1. merge is maybe too much. This would end by doing insert one by one, with at the end less control and almost the same verbosity.

2. Cause merge will probably use `entry` API , the function should take `Bson` by reference.

3. merge could return an iterator that do like [`drain()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain), so user could retrieve duplicate value. So the function `impl Fn(&str, Bson, Bson) -> Bson` could maybe return a `Ether::Left` `Ether::Right` But this would loose the ability to create a custom Bson. One way to fix it could be to use 3 case enum:

   ```rust
   enum Choice {
     Left,
     Right,
     None(Bson),
   ```

   This would give `impl Fn(&str, &Bson, &Bson) -> Choice`

4. linked-hash-map extend just use insert method: https://github.com/contain-rs/linked-hash-map/blob/f1ee0d032368e4912af9d4620bd0ec3857838f2e/src/lib.rs#L729
5. indexmap look better on this case, https://github.com/bluss/indexmap/blob/master/src/map.rs#L1045

**Comment by gembin** [comment]
Why not just define one simple behavior,   e.g. the right will always overwrite the left.
I think normally user just want to get one merged doc,  don't care about the duplicates.
If you want `b` overwrite `a`,  just call  `a.merge(b)`,   otherwise just call `b.merge(a)`.

**Comment by saghm** [comment]
Yes, that's the what I mentioned [here](https://github.com/mongodb/bson-rust/issues/192#issuecomment-664585900), and the most likely thing we'll be added. My follow-up comment was just brainstorming additional things we could potentially add to the API as well; if we added it, it would be in addition to `extend`, not instead of.

**Comment by NBSquare** [comment]
Just wanted to follow up on this issue to let you know that this functionality has already been implemented.
`Document` implements the [`Extend`](https://doc.rust-lang.org/stable/std/iter/trait.Extend.html) trait, and two documents can be merged simply by invoking `doc1.extend(doc2);` or similar. This will overwrite keys on the left-hand side.
