### ISSUE TITLE
RUST-504 ObjectId::new() doesn't work on wasm

### ISSUE THREAD

**Issue by sinhpham** [mongodb/bson-rust#199]
Due to using `std::time::SystemTime`.

A potential solution is exposing a `new_with_timestamp(n_secs_since_unix_epoch: u32) -> Self` constructor. People who want to run on wasm can supply their own timestamp.

**Comment by patrickfreed** [comment]
I filed [RUST-504](https://jira.mongodb.org/browse/RUST-504) to track the status of this. Thank you for filing an issue!

**Comment by abr-egn** [comment]
This was fixed in the 2.6.0 release.
