### ISSUE TITLE
Why the unsigned integers are not supported?

### ISSUE THREAD

**Issue by vityafx** [mongodb/bson-rust#218]
The README file mentions that the unsigned types are unsupported. But according to the [specification page](http://bsonspec.org/spec.html) they actually are:

```
byte       | 1 byte (8-bits)
int32      | 4 bytes (32-bit signed integer, two's complement)
int64      | 8 bytes (64-bit signed integer, two's complement)
uint64     | 8 bytes (64-bit unsigned integer)
double     | 8 bytes (64-bit IEEE 754-2008 binary floating point)
decimal128 | 16 bytes (128-bit IEEE 754-2008 decimal floating point)
```

This page is referred to from wikipedia and google doesn't give any better output. Is this not a valid specification? If not, when where is the official one?

**Comment by saghm** [comment]
The specification page you link to is the correct one. However, the section you're listing is just a definition of terms, not the list of types. If you look at the grammar below, you'll see that `uint64` is used for the "Timestamp" BSON type, but there is not any `uint64` type. The only numeric types in the grammar are "32-bit integer", "64-bit integer", "64-bit binary floating point", and "128-bit decimal floating point".

I agree that unsigned integer types would be useful, but unfortunately they are not part of the BSON spec, and the MongoDB database does not have any support for them.

**Comment by vityafx** [comment]
> The specification page you link to is the correct one. However, the section you're listing is just a definition of terms, not the list of types. If you look at the grammar below, you'll see that `uint64` is used for the "Timestamp" BSON type, but there is not any `uint64` type. The only numeric types in the grammar are "32-bit integer", "64-bit integer", "64-bit binary floating point", and "128-bit decimal floating point".
> 
> 
> 
> I agree that unsigned integer types would be useful, but unfortunately they are not part of the BSON spec, and the MongoDB database does not have any support for them.
> 
> 
> 
> 
> 
> 

Thank you for your reply, it is just really frustrating as to why it is not supported. I was looking for an explanation with details, but haven't found any. So the practice is to store numbers as strings then?

**Comment by octopoulos** [comment]
You can store uint64 as int64 without any loss of data, and you can convert the int64 back to uint64 in your program. However, if you want mongo to sort data using that int64 key for example, then this will be an issue if it's supposed to be uint64.

**Comment by avri-schneider** [comment]
@kmahar 0 is greater than -1, yet smaller than its unsigned representation.
