### ISSUE TITLE
Decoding a a document with lossy utf8 conversion

### ISSUE THREAD

**Issue by thijsc** [mongodb/bson-rust#226]
I'm bumping the bson version in the Mongo C driver wrapper to the latest version in thijsc/mongo-rust-driver/pull/58.

We currently decode a few responses from Mongo with lossy utf8 conversion since we found out that sometimes invalid characters kan make it into error responses. We used `bson::decode_document_utf8_lossy` for this.

It looks like `bson::Document::from_reader` is the replacement. I don't see a way to have it use lossy encoding. Is there a way to achieve this?

**Comment by agolin95** [comment]
Tracked in: https://jira.mongodb.org/browse/RUST-648

**Comment by patrickfreed** [comment]
Fixed in #232, and will be included in the next release.
