### ISSUE TITLE
Add support for borrowed deserialization

### ISSUE THREAD

**Issue by TedDriggs** [mongodb/bson-rust#231]
I have a struct like this:

```rust
#[derive(Deserialize)]
struct Example<'a> {
    #[serde(borrow)]
    field: Option<Cow<'a, str>>,
    #[serde(borrow, default)]
    other_field: Vec<Cow<'a, str>>,
}
```

I'd like to use it with this crate, but the `DeserializeOwned` bound gets in the way.

I think the issue is that deserialization goes through `Document`, which in turn requires ownership of strings etc. inside it. Is that correct, and if so could that be mitigated by having a `bson::borrow::Bson` which points into a backing `&'a [u8]`?

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-688

**Comment by agolin95** [comment]
Hi Ted, just wanted to follow up to let you know this is still on our radar. We'll be taking a deeper look after we wrap up the work and conversation on https://github.com/mongodb/bson-rust/pull/229

**Comment by patrickfreed** [comment]
This is implemented in https://github.com/mongodb/bson-rust/commit/7ccf82b3dc66141d8292a5c1e253362abaa13d5c and will be included in the next release.
