### ISSUE TITLE
Deserialisation of a Decimal128 allows user provided readers to view uninitalised data

### ISSUE THREAD

**Issue by 5225225** [mongodb/bson-rust#251]
The following lines are unsound when given a user defined reader who is allowed to read from the buffer `local_buf`.

https://github.com/mongodb/bson-rust/blob/0ebb96c8a0ff32f9da17eef3b3a7d3db781862a9/src/de/mod.rs#L164-L173

I can't run a test case in miri, but the following fuzzing harness with `--sanitizer=memory` given will find it.

```rust
#![no_main]
#[macro_use] extern crate libfuzzer_sys;
extern crate bson;

use bson::Document;
use std::io::Cursor;

fuzz_target!(|buf: &[u8]| {
    struct HostileReader<R> {
        reader: R,
    }

    impl<R: std::io::Read> std::io::Read for HostileReader<R> {
        fn read(&mut self, buf: &mut [u8]) -> Result<usize, std::io::Error> {
            let v: usize = buf.iter().copied().map(|x| x as usize).sum();

            self.reader.read(buf)
        }
    }

    let mut r = HostileReader { reader: Cursor::new(&buf[..]) };

    let _ = Document::from_reader(&mut r);
});
```

An implementation of `std::io::Read` which reads from the buffer given instead of purely writing to it is *discouraged*, but `Read` is a safe trait, so it's not unsafe to do this.

There's the https://doc.rust-lang.org/std/io/trait.Read.html#method.initializer method, but it's unstable, tracking issue: https://github.com/rust-lang/rust/issues/42788

Failing that, I think the only reasonable thing to do is to just zero out the buffer (just like what's done above for the case where `decimal128` is not enabled). 

---

As a side note, does anyone know *why* decimal::d128::from_raw_bytes is unsafe? We're calling it with completely unchecked values from the user, so if there's any values for which it can cause UB, that doesn't sound safe. I might open an issue on their end asking for clarification as to why it's unsafe.

I had a look at the documentation there there's no indication as to what you need to do to be safe calling it. Looks like from_hex does basically the same thing as from_raw_bytes, so it *shouldn't* be unsafe?

**Comment by abr-egn** [comment]
Thanks for the report!  This has been fixed in commit [a9eba30](https://github.com/mongodb/bson-rust/commit/a9eba30cc1ef2b4ae24f60880f435cf8415bcc9d).
