### ISSUE TITLE
remove DbPointer,MaxKey,MinKey and more  Database related types

### ISSUE THREAD

**Issue by zhuxiujia** [mongodb/bson-rust#291]
remove DbPointer,MaxKey,MinKey，ObjectId  and more  Database related types。

For any other purpose, you wouldn't need these things. Unless the library can only be used with mongodb！（Maybe the crate should be called ``` mongodb-bson ``` Rather than  ``` bson-rust ```） 

I'm sorry to bother you with my obsession with cleanliness

I think we should provide an extension type to extend new types that may be used。

**Comment by kmahar** [comment]
Hi @zhuxiujia, thank you for reaching out.

This library provides an implementation of the BSON specification: https://bsonspec.org/spec.html 

The types you mention are all types defined in the specification itself.

While we realize some types may be used more commonly than others, depending on particular use cases, we would like to keep the complete implementation of the specification in a single crate.
