### ISSUE TITLE
[Idea] May be it's helpful to provide some getter method for nullable field in document?

### ISSUE THREAD

**Issue by WindSoilder** [mongodb/bson-rust#293]
I think it's common that some fields in a document can be `null` (especially documents from `mongodb`).

So maybe it's helpful to provide some method for these scenario?

For now I have to implement a helper function like this: 

```rust
use bson::{Bson, Document, document::ValueAccessError};

// the Result is my custom define type.
pub fn get_option_str<'a>(doc: &'a Document, key: &str) -> Result<Option<&'a String>> {
    match doc.get(key) {
        Some(&Bson::String(ref v)) => Ok(Some(&v)),
        Some(&Bson::Null) => Ok(None),
        Some(_) => Err(ValueAccessError::UnexpectedType),
        None => Err(ValueAccessError::NotPresent),
    }
}
```

**Comment by patrickfreed** [comment]
Hi @WindSoilder, thanks for the suggestion!

While we see the potential value in an API like this, we think it might be hard for users to reason about when `ValueAccessError::NotPresent` vs `Ok(None)` will be returned. Also, we feel that `serde` is generally more suited to addressing these kinds of tasks and should be preferred over working directly with `Document`.

For example, if we have the following struct:
```rust
#[derive(Serialize, Deserialize)]
struct Foo {
    bar: Option<String>,
}
```

Then all of the following will deserialize properly:
```rust
let empty: Foo = bson::from_document(doc! { })?; // Foo { bar: None }
let some: Foo = bson::from_document(doc! { "bar": "some string" })?; // Foo { bar: "some string" }
let null: Foo = bson::from_document(doc! { "bar": Bson::Null })?; // Foo { bar: None }
```

For those reasons, we've decided not to include such methods in `Document`'s API. Thanks again for the suggestion though, and please let us know if you have any other questions on this!
