### ISSUE TITLE
uuid_as_binary is bad with other formats

### ISSUE THREAD

**Issue by Caellian** [mongodb/bson-rust#301]
I'm writing a server where I use MongoDB for storage but the frontend uses JSON for data.
I have to use `uuid_as_binary` on my data so it's properly stored in the DB, but it messes up how the frontend receives that data (it's formatted as Binary struct).

I created a [Gist](https://gist.github.com/Caellian/0440d5fd3bb31d7ff1c8044b17057d7a) with the code I threw together to fix this issue, but your serialization module isn't public so I can't make it compile.

Anyway, I was wondering why you aren't using something similar from your side in `serde_helpers` so that they default to `chrono`'s and `uuid`'s preferred formats _unless_ the (de)serializer isn't yours (where special support is needed).

I believe the only other way to go around this quirk is to not use derive and instead manually impl Serialize and Deserialize for all structs that use chrono and/or uuid which is a lot of work for my small server.

It's clumsy to use this:
```ts
export interface UUIDBin {
	base64: string;
	subType: string;
}

export interface UUID {
	$binary: UUIDBin;
}

export function uuid_path(uuid: UUID): string {
	return uuid.$binary.base64;
}
```
from the frontend.

Also, why not use something similar to intercept time and uuid structs from the Serializer `serialize_some` and avoid people having to use `serde_helpers` altogether?

**Comment by Caellian** [comment]
After toying around with the sources, I realized what I'm asking requires `min_specialization` feature available in nightly as all types in serde_helpers already implement `(De)Serializable`.

I'll implement this in my fork and you can merge it once `min_specialization` goes into stable.

**Comment by patrickfreed** [comment]
Another option, which may or may not be any more convenient, is to still use `derive` but have separate models for DB / frontend interaction that can be converted between each other via `From`/`Into`.

You can also use an [extended JSON parser](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) in in the frontend to handle the custom format (e.g. [`js-bson`](https://github.com/mongodb/js-bson)).

**Comment by Caellian** [comment]
Yeah, I'll probably have to model frontend responses anyway for validation.
Didn't know about `js-bson` so thanks for pointing it out.

I'll still implement suggested behavior for backend -> frontend communication on my fork so you might want to check it out when `min_specialization` comes into stable. I have to use nightly bc of Rocket so it makes no difference for me and I prefer default serialization of the `uuid` crate.
