### ISSUE TITLE
decode_document and encode_document listed but not provided in the crate.

### ISSUE THREAD

**Issue by r0bertcode** [mongodb/bson-rust#312]
On the documentation as well as the API guide, they show these functions as public, but they are not provided.

Have these been removed in previous versions? Is there a replacement?

**Comment by patrickfreed** [comment]
These functions were replaced by `Document::from_reader` and `Document::to_writer` respectively before the 1.0 release. Could you link to where in the documentation these methods are still listed so we can update them? Thanks!

**Comment by r0bertcode** [comment]
I just realized I was looking at a version prior to the 1.0 release, sorry for the confusion and thanks for the response.
