### ISSUE TITLE
Any way to deserialize "shell mode" json?

### ISSUE THREAD

**Issue by igorsol** [mongodb/bson-rust#339]
The documentation of `extjson` module states it only supports extended json V2. That's clear.
But `mongosh` still produces "shell mode" json, looking like this for example:

``` js
{
    clusterTime: Timestamp({ t: 1642587525, i: 1 }),
    signature: {
      hash: Binary(Buffer.from("0000000000000000000000000000000000000000", "hex"), 0),
      keyId: Long("0")
    }
}
```
Is there any way to deserialize this in rust application?

**Comment by isabelatkinson** [comment]
Hi @igorsol, thank you for filing this issue! We currently do not support deserializing from/parsing shell mode JSON. I recommend converting your shell mode JSON to exended JSON directly in the shell with the following command:

```
EJSON.stringify({your query here}.toArray())
```

Please let us know if you have any further questions!

**Comment by igorsol** [comment]
Thank you for the answer. I have no more questions.
