### ISSUE TITLE
`bson::Uuid` does not implement `Eq`, cannot be used as a key in a `HashMap`

### ISSUE THREAD

**Issue by remopas** [mongodb/bson-rust#351]
Hi,

I wish to use `bson::Uuid` as a key in a `HashMap`. Currently this is not possible because it only implements `PartialEq` and not `Eq`.  Is there any specific reason that limits implementing `Eq` for this type? `uuid::Uuid` does implement `Eq` so for me it would make sense if it reproduces the same interface.

Many Thanks!

**Comment by patrickfreed** [comment]
Thanks for filing this issue! You're correct that there isn't any meaningful reason why `bson::Uuid` doesn't implement `Hash` or `Eq`, and in fact the next release (2.2.0) will add implementations for those traits (see #345). In the meantime, you can start using the latest beta release (2.2.0-beta.1) to get that functionality today.
