### ISSUE TITLE
linked-hash-map leaks memory in bson 1.x

### ISSUE THREAD

**Issue by TheDan64** [mongodb/bson-rust#363]
## Versions/Environment
1. What version of Rust are you using? 
1.61.0
2. What operating system are you using?
Ubuntu 20.04
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
Not using mongodb (still on the old mongoc_driver) and for bson it's `https://github.com/rust-lang/crates.io-index#bson:1.2.4`
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`)
4.4
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
sharded

## Describe the bug

bson 1.x uses the `linked-hash-map` crate, which I've shown to leak memory here: https://github.com/contain-rs/linked-hash-map/issues/110

This is causing issues for us as we're still stuck using bson 1.x for the foreseeable future. We were wondering if it'd be possible to release a new 1.2.5 release which uses indexmap instead of linked-hash-map just like bson 2 does. The `linked-hash-map` crate is in maintenance mode and has very little activity. It seems unlikely to get patched.

**To Reproduce**
1. Use bson 1.x
2. Make inserts into documents
3. Check for memory leaks

**Comment by eddyb** [comment]
@TheDan64 Do you have some testing that shows this without running out of memory, like https://github.com/contain-rs/linked-hash-map/issues/110#issuecomment-1166219357 does? (which then makes leak checkers think all allocated memory is leaked, since the process aborted)

**Comment by TheDan64** [comment]
Closing as my repro turned out to be a false positive & haven't been able to repro a true positive since. Will reopen if I manage to do so.
