### ISSUE TITLE
Test files are missing, which prevents tests from being run.

### ISSUE THREAD

**Issue by emixa-d** [mongodb/bson-rust#368]
>  Make sure you have read CONTRIBUTING.md completely before you file a new issue! 

This file does not exist, so I can't read it.

## Versions/Environment
2. What operating system are you using?

Guix (with the new WIP antioxidant-build-system instead of cargo-build-system; the latter often does not run tests but the former does).

Other questions: I'm not using MongoDB.

## Describe the bug

The test files are missing from the the archive at `crates.io`.  Because antioxidant (the new thing that is developed for Guix to build Rust packages) wants to _run_ the tests (unlike the previous system we had in place), this causes build failures when building the package rust-bson@2.0.1:

```
[...]
error[E0583]: file not found for module `tests`
   --> src/lib.rs:337:1
    |
337 | mod tests;
    | ^^^^^^^^^^
    |
    = help: to create the module `tests`, create file "src/tests.rs" or "src/tests/mod.rs"

error[E0432]: unresolved import `crate::tests::LOCK`
   --> src/oid.rs:226:5
    |
226 | use crate::tests::LOCK;
    |     ^^^^^^^^^^^^^^^^^^ no `LOCK` in `tests`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0583.
For more information about an error, try `rustc --explain E0432`.
error: in phase 'build': uncaught exception:
%exception #<&invoke-error program: "rustc" arguments: ([lots of arguments]") exit-status: 1 term-signal: #f stop-signal: #f>
```

To be clear, this is about the first error: "file not found for module `tests`", not the second.
Also, this can be worked-around in Guix (by switching to a git checkout instead of a `crates.io` download), but it would be simpler if upstreams didn't remove tests in the first place.

This is kind of the opposite of <https://github.com/mongodb/bson-rust/issues/202>; I don't know whether reducing crate size or running tests is considered more important -- if the former, feel free to close.

**Comment by isabelatkinson** [comment]
Hi @emixa-d, thank you for filing this issue! We don't currently support antioxidant, so I'm going to close this out to maintain the reduced crate size. If you'd like to run the tests, I'd recommend cloning this repo directly and running them from there. Please let me know if you have any further questions or comments!

**Comment by emixa-d** [comment]
Ok, is fine, just wanted to make sure it was not an oversight.
