### ISSUE TITLE
Extremely Unintuitive

### ISSUE THREAD

**Issue by elibroftw** [mongodb/bson-rust#391]
To prove my point, suppose I return the following serialized:

```rs
#[derive(Clone, Debug, Deserialize, Serialize)]
struct BlogPost {
    _id: ObjectId,
    title: String,
    content: String,
    published: DateTime
}
```

your job is to use published in a frontend like Tera. Is it post.published? No of course not, just like the id field, datetime is not a primitive. It must be post.published['$date']. Right? Right guys? 

it's neither of these. we shouldn't have to 

```rs
let x = to_pretty_string(
        d[0].get("published").unwrap()
    ).unwrap();
    print!("{x}");
```

just to figure out what sort of black box bson serialization is operating under.

<details>
<summary>SPOILER</summary>

The answer of course is so obvious. I shouldn't even post it. Only an idiot wouldn't know the most intuitive and 100% intelligent design developer with an IQ > 9000 `post.published['$date']['$numberLong']`

Actually this isn't it either, this is just an integer! To get a date string we need to figure out we need to see the serde helpers over  here https://docs.rs/bson/latest/bson/serde_helpers/index.html and then for each of these formats we just pick out the format which we need. Only a loser and idiot would need to google how each of these formats look like. Definitely a reasonable assumption to bury these helpers and reference only one of them ever in the Datetime docs. If you needed to use Google to figure out which of these formats, you should just get better at programming. 

Ah yes, so we figured out `bson_datetime_as_rfc3339_string` is the way to go. But doesn't work for me since I can't get struct filters to work because of this other error

```
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: BsonDeserialization(DeserializationError { message: "invalid type: map, expected a string" }), labels: {}, wire_version: None, 
source: None }', src\blog.rs:48:75
```

It's probably because I have to delete the existing documents or perform a migration which isn't noted anywhere. goddamn!

</details>

Back to Python I go!

**Comment by kmahar** [comment]
@elibroftw I can see that you’re frustrated, but the tone of this post isn’t an acceptable way to communicate with others and isn’t something we tolerate in our GitHub discussions. I’m going to close and lock this issue. Please feel free to open a new one with more appropriate and respectful wording to ask any questions or make any suggestions you have.
