### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by elibroftw** [mongodb/bson-rust#392]
The docs don't indicate how the serde serialization will be performed on ObjectID or Datetime. I suggest improving the documentation for objectID and Datetime to show how access the fields in a frontend that expects json.

I also ask to improve the datetime documentation to include how to show the date in different formats.

**Comment by patrickfreed** [comment]
Thanks for filing this issue, I've gone ahead and updated the docs for `DateTime` and `ObjectId` to be clearer about how they interact with serde. Let us know if you have any further feedback.
