### ISSUE TITLE
Feature Request: Consider CompactString for Document keys

### ISSUE THREAD

**Issue by TheDan64** [mongodb/bson-rust#420]
It seems like `Document` is basically just a HashMap with String keys. It's pretty common to have relatively short and readable keys (ie `_id`), so [CompactString](https://docs.rs/compact_str/0.7.1/compact_str/) seems like it could be a useful optimization to reduce heap allocations, memory fragmentation, and improve cache locality in a lot of cases where you have larger documents with a lot of keys

**Comment by isabelatkinson** [comment]
Hi @TheDan64, unfortunately we won't be able to do this for a few reasons. `compact_str` is a pre-1.0 crate, and we prefer to avoid exposing unstable types in our public API. Relatedly, changing the current type for document keys would be a breaking change for users who iterate over keys or key/value pairs and expect the keys to be `String`s. To mitigate this, we'd need to map `CompactString`s to `String`s in these iterators, which would negate some of the performance and memory consumption improvements of using `CompactString`. If you're looking for these types of improvements, [`RawDocumentBuf`](https://docs.rs/bson/latest/bson/struct.RawDocumentBuf.html) might be of interest.

Please let us know if you have any further questions or other feature requests!
