### ISSUE TITLE
Operating on BSON Decimal128 type

### ISSUE THREAD

**Issue by jvliwanag** [mongodb/bson-rust#484]
Seeking guidance on how to operate on Decimal128 bson type such as value comparisons, additions, etc.

I noticed that bson-rust used [decimal](https://crates.io/crates/decimal) crate at one point but opted to make it internal. Is decimal byte compatible with Decimal128? Is it advisable to use [from_raw_bytes](https://alkis.github.io/decimal/decimal/struct.d128.html#method.from_raw_bytes) to convert to Decimal?

**Comment by abr-egn** [comment]
The `bson` crate doesn't provide any manipulation beyond reading or printing strings.  The binary representation is a standard IEEE 754-2008 value, so anything that uses that representation should work fine, including the `decimal` crate.

**Comment by jvliwanag** [comment]
Unfortunately found more details on [RUST-960](https://jira.mongodb.org/browse/RUST-960) that this won’t work. Haven’t found any crate that works yet. Looks like the only correct way right now is to convert to string and to reparse it on one of the rust decimal implementations. It won’t be performant though.
