### ISSUE TITLE
Add chrono::TimeDelta to mongodb::bson::DateTime

### ISSUE THREAD

**Issue by ChanManChan** [mongodb/bson-rust#489]
Is there a better way to add chrono::Duration to bson::DateTime without converting to chrono::DateTime?

currently I'm doing this
expires_at: DateTime::from_millis(now.timestamp_millis() + duration.num_milliseconds()),

**Comment by isabelatkinson** [comment]
Hi @ChanManChan, there is currently no way to add a `chrono::Duration`/`chrono::TimeDelta` directly to a `bson::DateTime`. Your current approach looks reasonable. Enabling the `chrono-0_4` feature flag if you have not done so already will also allow you to convert more easily between `bson::DateTime` and `chrono::DateTime` via the [`to_chrono`](https://docs.rs/bson/latest/bson/datetime/struct.DateTime.html#method.to_chrono) and [`from_chrono`](https://docs.rs/bson/latest/bson/datetime/struct.DateTime.html#method.from_chrono) methods.
