### ISSUE TITLE
RUST-2019 Formatter for `Bson` ignores pretty printing `{:#}`

### ISSUE THREAD

**Issue by mahmoud-moursy** [mongodb/bson-rust#491]
## Versions/Environment
1. What version of Rust are you using? 

rustc 1.82.0-nightly (506052d49 2024-08-16)

2. What operating system are you using?

Linux

3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)

- `bson`: `registry+https://github.com/rust-lang/crates.io-index#bson@2.11.0`
- `mongodb`: N/A

4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
N/A
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
N/A

## Describe the bug

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
Expected behaviour:

`Bson` formatting outputs the following:
```json5
{
  "key": "Hello world!"
}
```
What actually happens:

`Bson` formatting outputs the following:
```json5
{ "key": "Hello world!" }
```
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?

If you implemented `Display` manually, then you need to manually check if the user passed in pretty-printing
as a parameter and then change your formatting based on that.

You can check it using `formatter.alternate()` in your `Display` implementation.

* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
The issue has likely existed for as long as the crate has.
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
Nope. Only one, specifically. Formatting with `{:#?}` produces correctly-formatted output.
* If you know how to reproduce this bug, please include a code snippet here:
```rs
let my_hashmap = HashMap::from([
  ("hello", "world!")
]);

let bson_document = bson::to_document(&my_hashmap);

// Incorrect formatting:
println!("{bson_document:#}");

// This, however, is correctly formatted:
println!("{bson_document:#?}");
// It is probably correctly formatted because the derive(Debug) implementation was used.
```

Thank you.

**Comment by abr-egn** [comment]
Thank you for the well-written ticket!

You're quite right that we're not respecting that flag currently; I've filed RUST-2019 to track that.  This won't be high priority in our plan for this quarter but we'd certainly welcome a contribution to add it 🙂
